In [5]:
from sympy import *
import numpy as np

In [6]:
from sympy.interactive.printing import init_printing
init_printing(use_unicode=True)

In [9]:
u=np.array([-1,2,3])

v=np.array([1,2,3])

In [10]:
print(u+v)

[0 4 6]


In [11]:
print(u-v)

[-2  0  0]


In [12]:
np.dot(u,v)

In [13]:
u*v

array([-1,  4,  9])

In [14]:
np.cross(u,v)

array([ 0,  6, -4])

In [16]:
M=Matrix([[1,2],[3,4]])
M

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [17]:
i,j=symbols('i,j')

In [18]:
def f(i,j):
    return i**2+j**2

In [21]:
M1=Matrix(2,4,f)
M1

⎡0  1  4  9 ⎤
⎢           ⎥
⎣1  2  5  10⎦

In [26]:
print ('cols of M1 are {} and rows of M1 are {}'.format(M1.cols,M1.rows))

cols of M1 are 4 and rows of M1 are 2


In [29]:
print ('the second elemet row 0 is {}'.format(M1[0,2]))

the second elemet row 0 is 4


In [28]:
M1[2]

In [30]:
M1[:,2:4]

⎡4  9 ⎤
⎢     ⎥
⎣5  10⎦

In [31]:
a=[1,2,3,4]

In [32]:
M=Matrix(2,2,a)

In [33]:
M

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [34]:
I=eye(3)

In [35]:
I

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [40]:
N=Matrix([[1,-1],[0,2]])
N

⎡1  -1⎤
⎢     ⎥
⎣0  2 ⎦

In [41]:
M*N

⎡1  3⎤
⎢    ⎥
⎣3  5⎦

In [42]:
N**3

⎡1  -7⎤
⎢     ⎥
⎣0  8 ⎦

In [44]:
Matrix(2,2,[i**2 for i in N])

⎡1  1⎤
⎢    ⎥
⎣0  4⎦

In [45]:
M

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [46]:
transpose(M)

⎡1  3⎤
⎢    ⎥
⎣2  4⎦

In [47]:
M.transpose()

⎡1  3⎤
⎢    ⎥
⎣2  4⎦

In [48]:
I.rank()

In [50]:
I.rank()

In [51]:
I.det()

In [52]:
det(I)

In [53]:
M.inv()

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

In [56]:
M**-1

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦